disabled = false
locale = "es-ES"
label = "Español"
weight = 1
title = "Fractalis"

[params]
  displayName = "ES"
  isoCode = "es"
  rtl = false
  logo = "img/logo.png"
  dateFormat = "2 January 2006"
  description = "Física y Química en cada escala"
  copyright = "© { year } Fractalis"

  [params.author]
    name = "Fractalis"
    email = "jogprofciencias@gmail.com"
    headline = "Física y Química en cada escala"
    bio = "**Fractal:** objeto geométrico en el que una misma estructura, fragmentada o aparentemente irregular, se repite a diferentes escalas y tamaños."
