# -- Main Menu --
# Navigation by course. More entries will be added as content folders
# for each course are created (3 ESO, 4 ESO, 1 BACH, 2 BACH).

[[main]]
  name = "2 ESO"
  pageRef = "/2eso"
  weight = 10

[[main]]
  name = "About me"
  pageRef = "/sobre-mi"
  weight = 90
