# -- Main Menu --
# Navegación por curso. Se añaden más entradas a medida que se creen
# las carpetas de contenido de cada curso.

[[main]]
  name = "2 ESO"
  pageRef = "/2eso"
  weight = 10

[[main]]
  name = "3 ESO"
  pageRef = "/3eso"
  weight = 20

[[main]]
  name = "4 ESO"
  pageRef = "/4eso"
  weight = 30

[[main]]
  name = "2 BACH"
  pageRef = "/2bach"
  weight = 40

[[main]]
  name = "Física"
  parent = "2 BACH"
  pageRef = "/2bach/fisica"
  weight = 10

[[main]]
  name = "Química"
  parent = "2 BACH"
  pageRef = "/2bach/quimica"
  weight = 20

[[main]]
  name = "Sobre mí"
  pageRef = "/sobre-mi"
  weight = 90
